method: grid
run_cap: 2
parameters:
  per_device_train_batch_size:
    value: 256
  torch_compile:
    values:
    - true
    - false
  mixed_precision:
    values:
    - fp16
  optim:
    values:
    - adamw_torch
  max_seq_length:
    values:
    - 512
  model_name_or_path:
    values:
    - roberta-base
