method: grid
run_cap: 8
parameters:
  per_device_train_batch_size:
    values:
    - 64
  mixed_precision:
    values:
    - fp16
  optim:
    values:
    - adamw_torch
  max_seq_length:
    values:
    - 256
  model_name_or_path:
    values:
    - roberta-base
  dataloader_num_workers:
    values:
    - 0
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64