method: grid
name: embedding-size
description: Comparing divisibility of embedding size with speed
run_cap: 5
parameters:
  per_device_train_batch_size:
    values:
    - 128
  mixed_precision:
    values:
    - fp16
  optim:
    values:
    - adamw_torch
  max_seq_length:
    values:
    - 512
  model_name_or_path:
    values:
    - roberta-base
  resize_embeddings:
    values:
    - 0
    - 3
    - 8
    - 16
    - 64
