method: grid
name: Mixed precision
description: Comparing fp16 and fp32 training speeds
run_cap: 2
parameters:
  per_device_train_batch_size:
    values:
    - 64
  mixed_precision:
    values:
    - fp16
    - fp32
  optim:
    values:
    - adamw_torch
  max_seq_length:
    values:
    - 512
  model_name_or_path:
    values:
    - roberta-base